"""empty message

Revision ID: 1128175c9f6f
Revises: 3a7c0cb06724
Create Date: 2023-12-15 13:55:16.423942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1128175c9f6f'
down_revision = '3a7c0cb06724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.drop_constraint('users_id_key', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_users_id'), ['id'])
        batch_op.drop_constraint('users_id_fkey', type_='foreignkey')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_id_fkey', 'users', ['id'], ['id'], referent_schema='auth', onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_constraint(batch_op.f('uq_users_id'), type_='unique')
        batch_op.create_unique_constraint('users_id_key', ['id'])
        batch_op.create_index('ix_users_email', ['email'], unique=False)

    # ### end Alembic commands ###
