"""empty message

Revision ID: b186e8de0918
Revises: 2101898fc563
Create Date: 2023-12-21 16:34:12.923649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b186e8de0918'
down_revision = '2101898fc563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
